### ISSUE TITLE
svd browser/downloader?

### ISSUE THREAD

**Issue by psifertex** [ehntoo/binaryninja-svd#4]
For kicks I'm toying with integrating a web browser to be able to automatically download/extract SVD files from the new ARM url that I included in the other PR. It's not super critical and is a lot of code for a minor bit of functionality but if you're interested in accepting it, I'm still doing some tinkering/testing with it now. Let me know your thoughts. Very early screenshot:

<img width="1906" alt="Screen Shot 2020-09-26 at 9 44 50 PM" src="https://user-images.githubusercontent.com/140215/94353652-82aa3880-0041-11eb-891a-dbfffd95c239.png">

Yes, it's heavily inspired by the snippet editor UI. 😉

**Comment by ehntoo** [comment]
This sounds awesome! I'd love to have something like this.

**Comment by psifertex** [comment]
Sweet, I'll finish it off and submit a PR shortly. I've got an issue with the qt downloader doing threading right now that I'm probably just going to be lazy and use requests instead for and it should be pretty much done at that point.
