### ISSUE TITLE
"Can't process cluster without dim_index" when parsing NordicSemiconductor.nRF_DevicFamilyPack.8.32.1/nrf52.svd

### ISSUE THREAD

**Issue by JJJollyjim** [ehntoo/binaryninja-svd#8]
Hello

Is there any chance you've tested the loader with an nRF52 svd before? I haven't dived in to figure out what this means yet, but looking at https://siliconlabs.github.io/Gecko_SDK_Doc/CMSIS/SVD/html/group__cluster_level__gr.html it seems that DimIndex is optional.

I used pack version 8.32.1 from the Keil website, but it looks like all the versions can be obtained here: https://developer.nordicsemi.com/nRF5_SDK/pieces/nRF_DeviceFamilyPack/

**Comment by ehntoo** [comment]
Hi, I probably won't get a chance to look at this for a bit, but you might take a look at some of the SVD files used for nrf52 support in the rust ecosystem - they've got a number of patches that improve consistency and might get you moving until I get around to looking at this. :)

The SVD for the nRF52840 can be found here: https://github.com/nrf-rs/nrf52840-pac/blob/master/nrf52840.svd but I think all other family members also have similar peripheral access projects in the same parent repository.

**Comment by ehntoo** [comment]
I've come up with a fix for this after hitting it myself - it should be available in release 3.0.0 shortly https://github.com/ehntoo/binaryninja-svd/commit/7685bb1bf6089530aa3041e6c154531a1eac308f
